name: Release Build

on:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 获取日期 (yyyy-MM-dd)
        run: |
          DATE=$(date +'%Y-%m-%d')
          echo "DATE=$DATE" >> $GITHUB_ENV
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      
      - name: Decode keystore1
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: echo $KEYSTORE_BASE64 | base64 --decode > my-release-key.keystore
        
      - name: Decode keystore2
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: echo $KEYSTORE_BASE64 | base64 --decode > app/my-release-key.keystore
        
      - name: Build With Gradle
        run: |
          chmod +x gradlew
          ./gradlew assemblerelease  -Pandroid.injected.signing.store.file=my-release-key.keystore -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=aquarius_app -Pandroid.injected.signing.key.password=${{ secrets.KEYSTORE_KEY_PASSWORD }} --build-cache --parallel --daemon --warning-mode all
          
      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          for file in `find ~ -name "*.apk" -print`; do
            mv "$file" ${{ github.workspace }}/apk/
          done
      - name: Upload arm64-v8a To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NextPlayer-arm64-v8a-release-${{ env.DATE }}
          path: ${{ github.workspace }}/apk/NextPlayer-arm64-v8a-release-${{ env.DATE }}.apk
          overwrite: true
          compression-level: 0
      
      - name: Upload armeabi-V7a To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NextPlayer-armeabi-v7a-release-${{ env.DATE }}
          path: ${{ github.workspace }}/apk/NextPlayer-armeabi-v7a-release-${{ env.DATE }}.apk
          overwrite: true
          compression-level: 0
